python explainer_main.py --bmname Mutagenicity --graph-mode --num-gc-layers 3 --explainer-method pgexplainer --gpu --ckptdir "./ckpt/Mutagenicity" --multigraph-class 0  --prefix "pgexplainer_mutag" --lr 0.001 --size_c 0.001 --ent_c 8.0 --boundary_c 3 --inverse_boundary_c 12 --bloss-version "sigmoid" --epochs 601 --seed=42 &
python explainer_main.py --bmname Mutagenicity --graph-mode --num-gc-layers 3 --explainer-method pgexplainer --gpu --ckptdir "./ckpt/Mutagenicity" --multigraph-class 0  --prefix "pgexplainer_mutag" --lr 0.001 --size_c 0.001 --ent_c 8.0 --boundary_c 3 --inverse_boundary_c 12 --bloss-version "sigmoid" --epochs 601 --seed=15
wait
python explainer_main.py --bmname Mutagenicity --graph-mode --num-gc-layers 3 --explainer-method pgexplainer --gpu --ckptdir "./ckpt/Mutagenicity" --multigraph-class 0  --prefix "pgexplainer_mutag" --lr 0.001 --size_c 0.001 --ent_c 8.0 --boundary_c 3 --inverse_boundary_c 12 --bloss-version "sigmoid" --epochs 601 --seed=10 &
python explainer_main.py --bmname Mutagenicity --graph-mode --num-gc-layers 3 --explainer-method pgexplainer --gpu --ckptdir "./ckpt/Mutagenicity" --multigraph-class 0  --prefix "pgexplainer_mutag" --lr 0.001 --size_c 0.001 --ent_c 8.0 --boundary_c 3 --inverse_boundary_c 12 --bloss-version "sigmoid" --epochs 601 --seed=3
wait
python explainer_main.py --bmname Mutagenicity --graph-mode --num-gc-layers 3 --explainer-method pgexplainer --gpu --ckptdir "./ckpt/Mutagenicity" --multigraph-class 0  --prefix "pgexplainer_mutag" --lr 0.001 --size_c 0.001 --ent_c 8.0 --boundary_c 3 --inverse_boundary_c 12 --bloss-version "sigmoid" --epochs 601 --seed=0 &
python explainer_main.py --bmname Mutagenicity --graph-mode --num-gc-layers 3 --explainer-method pgexplainer --gpu --ckptdir "./ckpt/Mutagenicity" --multigraph-class 0  --prefix "pgexplainer_mutag" --lr 0.001 --size_c 0.001 --ent_c 8.0 --boundary_c 3 --inverse_boundary_c 12 --bloss-version "sigmoid" --epochs 601 --seed=1
wait
python explainer_main.py --bmname Mutagenicity --graph-mode --num-gc-layers 3 --explainer-method pgexplainer --gpu --ckptdir "./ckpt/Mutagenicity" --multigraph-class 0  --prefix "pgexplainer_mutag" --lr 0.001 --size_c 0.001 --ent_c 8.0 --boundary_c 3 --inverse_boundary_c 12 --bloss-version "sigmoid" --epochs 601 --seed=5 &
python explainer_main.py --bmname Mutagenicity --graph-mode --num-gc-layers 3 --explainer-method pgexplainer --gpu --ckptdir "./ckpt/Mutagenicity" --multigraph-class 0  --prefix "pgexplainer_mutag" --lr 0.001 --size_c 0.001 --ent_c 8.0 --boundary_c 3 --inverse_boundary_c 12 --bloss-version "sigmoid" --epochs 601 --seed=8
wait
python explainer_main.py --bmname Mutagenicity --graph-mode --num-gc-layers 3 --explainer-method pgexplainer --gpu --ckptdir "./ckpt/Mutagenicity" --multigraph-class 0  --prefix "pgexplainer_mutag" --lr 0.001 --size_c 0.001 --ent_c 8.0 --boundary_c 3 --inverse_boundary_c 12 --bloss-version "sigmoid" --epochs 601 --seed=69 &
python explainer_main.py --bmname Mutagenicity --graph-mode --num-gc-layers 3 --explainer-method pgexplainer --gpu --ckptdir "./ckpt/Mutagenicity" --multigraph-class 0  --prefix "pgexplainer_mutag" --lr 0.001 --size_c 0.001 --ent_c 8.0 --boundary_c 3 --inverse_boundary_c 12 --bloss-version "sigmoid" --epochs 601 --seed=101